version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: container_mysql_hotelaria
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

  back-end:
    image: node:latest
    container_name: container_back-end_tech
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    working_dir: /usr/app
    volumes:
      - ./back_end:/usr/app
    command: bash -c "npm install && npx sequelize db:create && npx sequelize db:migrate && npx sequelize db:seed:all && npm run dev"

  front-end:
    image: node:latest
    container_name: container_front-end_tech
    restart: always
    depends_on:
      - back-end
    env_file:
      - ./.env
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      - REACT_APP_BACK_PORT=${SERVER_PORT}
      - REACT_APP_BACK_HOST=back-end
    working_dir: /usr/app
    volumes:
      - ./front_end:/usr/app
    command: bash -c "npm install && npm start"

volumes:
  mysql_data:
